version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    ports:
      - "9090:9090" # Map container port 9090 to localhost
    environment:
      - POSTGRES_HOST=dpg-ctd4tb68ii6s738ufpt0-a.ohio-postgres.render.com
      - POSTGRES_PORT=5432
      - POSTGRES_USER=akrom
      - POSTGRES_PASSWORD=B3Yg56SFXBEBGzDlT1nz8kRbFCLWyb0c
      - POSTGRES_DATABASE=task_gs6j
      - REDIS_URL=rediss://default:AblCAAIjcDE5MDVhYzJmZDRiZGE0NjQxOTlkM2I2NDdjNzE1YjA5N3AxMA@first-tomcat-47426.upstash.io:6379
      - REDIS_HOST=first-tomcat-47426.upstash.io
      - REDIS_PORT=6379
      - REDIS_PASSWORD=AblCAAIjcDE5MDVhYzJmZDRiZGE0NjQxOTlkM2I2NDdjNzE1YjA5N3AxMA
      - SECRET_KEY_JWT=OUCdnbfzVa30S+nVBeYy1KMlTfeQUzpiHIqXJ51+2ec=
      - HTTP_PORT=:9090
      - HTTP_SCHEME=http
      - ENVIRONMENT=release
      - SERVICE_NAME=Task
      - VERSION=1.0
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"
    command: redis-server --requirepass AblCAAIjcDE5MDVhYzJmZDRiZGE0NjQxOTlkM2I2NDdjNzE1YjA5N3AxMA
